version: '3'

# https://jupyter-docker-stacks.readthedocs.io/en/latest/index.html
services:
  app:
    # build: .


    # image: jupyter/datascience-notebook

    # build:
    #   context: ./
    #   dockerfile: Dockerfile_ubuntu

    build:
      context: ./
      dockerfile: Dockerfile



    ports:
      - "8888:8888"
    volumes: 
      # - "./src:/home/src"
      - "./:/home/jovyan/work"
    environment: 
      - GRANT_SUDO=yes
  